version: '3.8'
services:

  # database:
  #   image: postgres:13-alpine
  #   container_name: tripsit_database
  #   restart: always
  #   env_file: .env
  #   ports:
  #     - 5630:5432
  #   volumes:
  #     - tripsit_data:/var/lib/postgresql/data
  #     - tripsit_data:/docker-entrypoint-initdb.d

  web:
    container_name: tripsit_web
    build: ./nginx
    restart: always
    ports:
      - 8000:443/tcp
      - 8080:80/tcp
    extra_hosts:
      tripsit.local: 127.0.0.1
    volumes:
      - ./packages/web-main/docroot:/usr/share/nginx/tripsit_web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

  psybot:
    container_name: tripsit_psybot
    build: ./packages/psybot
    restart: always
    # volumes:
    #   - ./packages/psybot

  chat:
    container_name: tripsit_chat
    build: ./packages/chat
    restart: always
    ports:
      - 9000:9000/tcp
    extra_hosts:
      tripsit.local: 127.0.0.1
    volumes:
      - ./packages/chat/volume:/var/opt/thelounge

# volumes:
#   tripsit_data:
#     name: tripsit_data
#     driver: local
